[package]
authors = ["Jorge Aparicio <jorge@japaric.io>"]
categories = ["command-line-utilities", "development-tools"]
description = "Proxy for LLVM tools like llvm-nm, llvm-objdump and llvm-size"
documentation = "https://github.com/rust-embedded/cargo-binutils#cargo-binutils"
keywords = ["llvm", "size", "objdump", "nm"]
license = "MIT OR Apache-2.0"
name = "cargo-binutils"
readme = "README.md"
repository = "https://github.com/rust-embedded/cargo-binutils/"
version = "0.1.7"

[dependencies]
cargo_metadata = "0.9.1"
clap = "2.32.0"
failure = "0.1.1"
regex = "0.2.10"
rustc-cfg = "0.4.0"
rustc-demangle = "0.1.7"
rustc_version = "0.2.2"
serde = "1.0"
toml = "0.5.5"
walkdir = "2.1.4"